# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_weight_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buenos', models.CharField(blank=True, max_length=140, null=True)),
                ('malos', models.CharField(blank=True, max_length=140, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
        ),
    ]
