# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacion',
            name='buenos',
            field=models.IntegerField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='malos',
            field=models.IntegerField(blank=True, max_length=140, null=True),
        ),
    ]
