# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_weight_status'),
        ('verificacion', '0002_auto_20180308_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacion',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Weight'),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='buenos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificacion',
            name='malos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
