# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_weight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='user',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
