# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180308_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='statuss',
            field=models.CharField(choices=[('pendig', 'pendig'), ('aprove', 'aprove'), ('rechazado', 'rechazado')], default='pendig', max_length=50),
        ),
    ]
